name: rbac
version: '0.1.0.0'
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2017 Author name here
license: BSD3
github: shokohara/haskell-rbac
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - App
  dependencies:
  - base >=4.7 && <5
  - text
  - monad-logger
  - transformers
  - lens
  - gogol
  - gogol-core
  - gogol-compute
executables:
  rbac-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - rbac
    - text
tests:
  rbac-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - rbac
    - hspec
    - hspec-discover
    - bytestring
    - QuickCheck
    - quickcheck-text
